worlds:
    flat:
    - G4IGTMPCA
    - CBC4GL8UM
    newflat:
    - WTTSUGXC5
    - YBE2COJOY
    d:
    - 1LQLJ8TCB
    - 7YMMWOBTC
    - W3IBPSW1W
    - 9H3LDM20K
    - WIRVM43VS
    - YGQIG7XTV
    lore galore:
    - LKB425NA9
    - XEZ4EH5O1
