# Modified Spawns

# Demon Soldier override
[[modify]]
	return_immediately = true
	new_group = "progression_mobs"
	[modify.entity]
		entity = "lightningcraft:demon_soldier"
		ignoreSpawnConditions = true
		weight = 100
	[modify.gamestage]
		all_players = true
		gamestage = "deepdown"

# Artifical AoA staging
[[modify]]
	group = "all"
	new_group = "progression_mobs"
	[modify.entity]
		mod = "aoa3"
	[modify.gamestage]
		all_players = true
		gamestage = "advent"