# Modified Spawns

# Demon Soldier override
[[modify]]
	return_immediately = true
	new_group = "progression_mobs"
	[modify.entity]
		entity = "lightningcraft:demon_soldier"
		ignoreSpawnConditions = true
		weight = 100
	[modify.gamestage]
		gamestage = "deepdown"

# Artifical AoA staging
[[modify]]
	return_immediately = true
	new_group = "aoa_hostile"
	[modify.entity]
		mod = "aoa3"
	[modify.gamestage]
		gamestage = "advent"

# Artifical AoA staging
[[modify]]
	return_immediately = true
	group = "passive"
	[modify.entity]
		mod = "aoa3"
	[modify.gamestage]
		gamestage = "advent"

# Artifical AoA staging
[[modify]]
	return_immediately = true
	group = "ambient"
	[modify.entity]
		mod = "aoa3"
	[modify.gamestage]
		gamestage = "advent"

# Artifical AoA staging
[[modify]]
	return_immediately = true
	group = "aquatic"
	[modify.entity]
		mod = "aoa3"
	[modify.gamestage]
		gamestage = "advent"