# Removals

# Labyrinth Concussion Creeper removal
[[remove]]
	return_immediately = true
	dimension = 1024
	[remove.entity]
		matcher = "concussion"

# Labyrinth staged hostile removal
[[remove]]
	dimension = 1024
	[remove.gamestage]
		gamestage = "cavern"

[[remove]]
	group = "all"
	dimension = -11325